### ISSUE TITLE
Unable to use play_games_services.sign_in() function

### ISSUE THREAD

**Issue by johnkappa221** [cgisca/PGSGP#3]
Whenever I call the function play_games_services.sign_in(), there seems to be a popup which will end instantaneously and I would not be able to login.

**Comment by anisc** [comment]
hey @johnkappa221 did you figured it out? I have almost the same problem I was able to sign in once but then after that I can't I get a pop up that end instantly after and I'm not able to sign in, sign out or show leaderboard.

**Comment by cgisca** [comment]
@johnkappa221 , @anisc could you please try again with the latest released plugin 1.2.0 (https://github.com/cgisca/PGSGP/releases/tag/1.2.0) . Please check once again Readme, and follow up all the steps described there.

**Comment by tx350z** [comment]
[EDITED] I had the same problem. If the error code received by the sign_in call back is 8 (Permission Denied), the solution is to log into Google API Console and enable Google Drive API. The requirement for this API permission is not well documented.

**Comment by hamparawa** [comment]
If the error code is 4, you may need to check the SHA1 key that is entered when you configure the Google Play services. If you are using a debug build, you need to link it separately. https://developers.google.com/games/services/console/enabling#c_specify_client_id_settings

**Comment by Wallace99** [comment]
Does anyone have any pointers on fixing error code 8 when trying to sign in? I've enabled Google Drive API but no luck. I configured Google Play Services correctly as far as I know but only did it yesterday so wonder if it takes time to propagate or something?

EDIT: ah my bad, was missing app_id from the AndroidManifest

**Comment by Wallace99** [comment]
Got this error in logcat so guessing it's something related to my google play services setup
> 09-29 13:13:04.807 20781 20794 I StubGamesServiceBroker: Account did not meet criteria to check for unicorn [CONTEXT service_id=1 ]
09-29 13:13:04.824 20781 20794 I StubGamesServiceBroker: Returning the seamless Play Games install flow [CONTEXT service_id=1 ]
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: Getting service failed
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: java.lang.IllegalStateException
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at snw.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):14)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at aaov.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):40)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at skg.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):28)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at smx.onTransact(:com.google.android.gms@203315017@20.33.15 (040306-330018294):6)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at android.os.Binder.transact(Binder.java:507)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at ctg.onTransact(:com.google.android.gms@203315017@20.33.15 (040306-330018294):2)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at android.os.Binder.transact(Binder.java:507)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at aaod.onTransact(:com.google.android.gms@203315017@20.33.15 (040306-330018294):17)
09-29 13:13:04.832 20781 20794 E AbstractServiceBroker: 	at android.os.Binder.execTransact(Binder.java:573)
09-29 13:13:04.851 26400 26462 W GmsClient: IGmsServiceBroker.getService failed
09-29 13:13:04.851 26400 26462 W GmsClient: java.lang.IllegalStateException
09-29 13:13:04.851 26400 26462 W GmsClient: 	at android.os.Parcel.readException(Parcel.java:1701)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at android.os.Parcel.readException(Parcel.java:1646)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at smw.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):5)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at skx.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):82)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at rvu.a(:com.google.android.gms@203315017@20.33.15 (040306-330018294):7)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at rvy.run(:com.google.android.gms@203315017@20.33.15 (040306-330018294):4)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at sxf.b(:com.google.android.gms@203315017@20.33.15 (040306-330018294):12)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at sxf.run(:com.google.android.gms@203315017@20.33.15 (040306-330018294):7)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at tdf.run(:com.google.android.gms@203315017@20.33.15 (040306-330018294):0)
09-29 13:13:04.851 26400 26462 W GmsClient: 	at java.lang.Thread.run(Thread.java:762)
