### ISSUE TITLE
[CAUSED BY DEPRECATED API] Only works with default configuration and Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

### ISSUE THREAD

**Issue by oneseedfruit** [cgisca/PGSGP#58]
Godot 3.2.3
Android 10

This happens everytime when signing in if not using default configuration.

```
02-03 12:17:29.120  1494  3782 E Parcel  : Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-03 12:17:29.120  1494  3782 E Parcel  : java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-03 12:17:29.120  1494  3782 E Parcel  : 	at java.lang.Class.classForName(Native Method)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at java.lang.Class.forName(Class.java:454)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2981)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2883)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1160)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:8548)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:765)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:676)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1778)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:607)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1615)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1512)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1466)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1655)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
02-03 12:17:29.120  1494  3782 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:994)
02-03 12:17:29.120  1494  3782 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-03 12:17:29.120  1494  3782 E Parcel  : 	... 20 more
```

**Comment by oneseedfruit** [comment]
May be related: 

https://stackoverflow.com/questions/64383095/class-not-found-when-unmarshalling-com-google-android-gms-auth-api-signin-inter 

https://github.com/googlesamples/google-signin-unity/issues/12

**Comment by oneseedfruit** [comment]
Found out the fix:

![Screenshot_2021-02-03_20-05-48](https://user-images.githubusercontent.com/5054104/106744902-52ac1b00-665b-11eb-9290-c4f763ad2af8.png)

![Screenshot_2021-02-03_20-06-08](https://user-images.githubusercontent.com/5054104/106744911-55a70b80-665b-11eb-8d40-68e7b76c8147.png)
